### PR TITLE
Show instant schools logo in profile selection page

### LINKED ISSUE #147: Select profile page needs a hat logo
### Context

* Operating system: all
* Browser: all
* Phone / Device description (Make/Model/Form factor): all
* If testing on online demo, URL: https://instantschools-v2.learningequality.org

### Observed behavior

Select profile page still displays Kolibri logo:

user sign in - kolibri - google chrome_065

### Requested change

Replace with the IS hat logo.

### PR DESCRIPTION
**Pull request by christianmemije**
Fixes #147 
localhost_8000_user_ 2

### CODE REVIEW

File: kolibri_instant_schools_plugin/assets/src/views/select-profile-page/index.vue [hunk 1]
```diff
@@ -14,9 +14,7 @@
         />
       </template>
       <div>
-        <ui-icon class="app-bar-icon">
-          <logo />
-        </ui-icon>
+        <img class="app-bar-icon" src="../img/instant-school-logo.png">
```
Comment (radinamatic) [inline kolibri_instant_schools_plugin/assets/src/views/select-profile-page/index.vue]: @christianmemije 
Missing `ALT` attribute or `role="presentation"`!

Comment (christianmemije) [reply kolibri_instant_schools_plugin/assets/src/views/select-profile-page/index.vue]: @radinamatic Changes made!

**Comment by indirectlylit** [comment]
thanks!
